export const CREATE_TODO = `TODO_TYPES/CREATE_TODO`;
export const CLEAR_TODO = `TODO_TYPES/CLEAR_TODO`;
export const REMOVE_TODO = `TODO_TYPES/REMOVE_TODO`;
export const TODO_TO_DONE = `TODO_TYPES/TODO_TO_DONE`;

export const CLEAR_DONE = `TODO_TYPES/CLEAR_DONE`;
export const REMOVE_DONE = `TODO_TYPES/REMOVE_DONE`;
export const DONE_TO_TODO = `TODO_TYPES/DONE_TO_TODO`;